### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by ObzorchikPlus** [ucmateofficial/ucmate_bugs#1]
## Exception
* __User Action:__ ui error
* __Request:__ ACRA report
* __Content Country:__ RU
* __Content Language:__ ru-RU
* __App Language:__ ru_RU
* __Service:__ none
* __Version:__ 50.0
* __OS:__ Linux Android 11 - 30
<details><summary><b>Crash log </b></summary><p>

```
java.lang.ArrayIndexOutOfBoundsException: length=10; index=-1
	at java.util.ArrayList.get(ArrayList.java:439)
	at org.schabi.newpipe.offlinemusicplayer.Activity.MainActivity.onClick(MainActivity.java:28)
	at android.view.View.performClick(View.java:7520)
	at android.view.View.performClickInternal(View.java:7497)
	at android.view.View.access$3600(View.java:816)
	at android.view.View$PerformClick.run(View.java:28491)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:257)
	at android.app.ActivityThread.main(ActivityThread.java:8333)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:603)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)

```
</details>
<hr>

**Comment by ucmateofficial** [comment]
We are fixing bugs

**Comment by hadaralab** [comment]
i have same issue on android AOSP 9

![Screenshot_20220419-112902](https://user-images.githubusercontent.com/80859242/163962234-cfa50dce-36c5-42bc-a573-6d8eea20d697.png)

**Comment by hadaralab** [comment]
hi 

do have any update  if this issue will be solved or not

**Comment by ucmateofficial** [comment]
Sorry for late reply,
We are working on bug fixed,
We release new version soon, with new UI, new Features, and all bug fix please wait.
Thank you

**Comment by moteb757** [comment]
و
