### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by weatllica** [ucmateofficial/ucmate_bugs#3]
## Exception
* __User Action:__ requested stream
* __Request:__ https://www.youtube.com/watch?v=-Qih2Y4d_zM
* __Content Country:__ CN
* __Content Language:__ zh-CN
* __App Language:__ zh_CN
* __Service:__ YouTube
* __Version:__ 2.3
* __OS:__ Linux OnePlus/OnePlus7_CH/OnePlus7:11/RKQ1.201022.002/2202112154:user/release-keys 11 - 30
<details><summary><b>Crash log </b></summary><p>

```
org.schabi.newpipe.extractor.stream.StreamInfo$StreamExtractException: Could not get any stream. See error variable to get further details.
	at org.schabi.newpipe.extractor.stream.StreamInfo.extractStreams(StreamInfo.java:45)
	at org.schabi.newpipe.util.-$$Lambda$ExtractorHelper$YTHJjScxCJNO1LTCqs3IKy35iyY.call(lambda:5)
	at io.reactivex.rxjava3.internal.operators.single.SingleFromCallable.subscribeActual(SingleFromCallable.java:4)
	at io.reactivex.rxjava3.core.Single.subscribe(Single.java:4)
	at io.reactivex.rxjava3.internal.operators.single.SingleDoOnSuccess.subscribeActual(SingleDoOnSuccess.java:1)
	at io.reactivex.rxjava3.core.Single.subscribe(Single.java:4)
	at io.reactivex.rxjava3.internal.operators.maybe.MaybeFromSingle.subscribeActual(MaybeFromSingle.java:1)
	at io.reactivex.rxjava3.core.Maybe.subscribe(Maybe.java:6)
	at io.reactivex.rxjava3.internal.operators.maybe.MaybeConcatArray$ConcatMaybeObserver.drain(MaybeConcatArray.java:20)
	at io.reactivex.rxjava3.internal.operators.maybe.MaybeConcatArray$ConcatMaybeObserver.request(MaybeConcatArray.java:3)
	at io.reactivex.rxjava3.internal.operators.flowable.FlowableElementAtMaybe$ElementAtSubscriber.onSubscribe(FlowableElementAtMaybe.java:4)
	at io.reactivex.rxjava3.internal.operators.maybe.MaybeConcatArray.subscribeActual(MaybeConcatArray.java:2)
	at io.reactivex.rxjava3.core.Flowable.subscribe(Flowable.java:10)
	at io.reactivex.rxjava3.internal.operators.flowable.FlowableElementAtMaybe.subscribeActual(FlowableElementAtMaybe.java:1)
	at io.reactivex.rxjava3.core.Maybe.subscribe(Maybe.java:6)
	at io.reactivex.rxjava3.internal.operators.maybe.MaybeToSingle.subscribeActual(MaybeToSingle.java:1)
	at io.reactivex.rxjava3.core.Single.subscribe(Single.java:4)
	at io.reactivex.rxjava3.internal.operators.single.SingleSubscribeOn$SubscribeOnObserver.run(SingleSubscribeOn.java:1)
	at io.reactivex.rxjava3.core.Scheduler$DisposeTask.run(Scheduler.java:2)
	at io.reactivex.rxjava3.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:2)
	at io.reactivex.rxjava3.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:1)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:923)

```
</details>
<hr>

**Comment by weatllica** [comment]
![Screenshot_20220829-101303](https://user-images.githubusercontent.com/73425090/187109555-59ede895-f68f-462a-8f17-9667b075ea60.jpg)
